#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Cloud.Resource", IsApplication=false)]

namespace Cloud
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int ic_add_white_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int ic_check_grey600_18dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int ic_compliance = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int ic_health_safety = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int ic_list_badge_done = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int ic_list_badge_new = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int ic_location_on_grey600_18dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int ic_lock_grey600_18dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int ic_miscellaneous = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int ic_person_grey600_18dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int ic_personnel = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int ic_security = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int inbox_zero = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int login_screen_placeholder = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public static int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public static int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
